name: Build and Release Binaries
run-name: "Build and Release Binaries - ${{ github.event.inputs.tag_name }}"

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The tag name for this release'
        required: true
        default: 'v0.0.1'

jobs:
  build-and-release:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Linux AMD64 Binary
      run: |
        mkdir -p binaries/linux-amd64
        GOOS=linux GOARCH=amd64 go build -o binaries/linux-amd64/sitemap-generator

    - name: Build Linux ARM64 Binary
      run: |
        mkdir -p binaries/linux-arm64
        GOOS=linux GOARCH=arm64 go build -o binaries/linux-arm64/sitemap-generator

    - name: Build macOS AMD64 Binary
      run: |
        mkdir -p binaries/darwin-amd64
        GOOS=darwin GOARCH=amd64 go build -o binaries/darwin-amd64/sitemap-generator

    - name: Build macOS ARM64 Binary
      run: |
        mkdir -p binaries/darwin-arm64
        GOOS=darwin GOARCH=arm64 go build -o binaries/darwin-arm64/sitemap-generator

    - name: List output directory
      run: |
        echo "Listing binaries directory for debugging:"
        ls -R binaries

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        release_name: ${{ github.event.inputs.tag_name }}
        draft: false
        prerelease: false

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Upload Release Assets
      run: |
        gh release upload ${{ github.event.inputs.tag_name }} \
          binaries/linux-amd64/sitemap-generator#sitemap-generator-linux-amd64 \
          binaries/linux-arm64/sitemap-generator#sitemap-generator-linux-arm64 \
          binaries/darwin-amd64/sitemap-generator#sitemap-generator-darwin-amd64 \
          binaries/darwin-arm64/sitemap-generator#sitemap-generator-darwin-arm64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
