name: Build and Release Binaries
run-name: "Build and Release Binaries - ${{ github.event.inputs.tag_name }}"

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The tag name for this release'
        required: true
        default: 'v0.0.1'
      release_description:
        description: 'The description for this release'
        required: false
        default: 'new release!'

jobs:
  build-and-release:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Linux AMD64 Binary
      run: |
        GOOS=linux GOARCH=amd64 go build -o sitemap-generator-$GOOS-$GOARCH

    - name: Build Linux ARM64 Binary
      run: |
        GOOS=linux GOARCH=arm64 go build -o sitemap-generator-$GOOS-$GOARCH

    - name: Build macOS AMD64 Binary
      run: |
        GOOS=darwin GOARCH=amd64 go build -o sitemap-generator-$GOOS-$GOARCH

    - name: Build macOS ARM64 Binary
      run: |
        GOOS=darwin GOARCH=arm64 go build -o sitemap-generator-$GOOS-$GOARCH

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Create a Release and Upload Release Assets
      run: |
        gh release create ${{ github.event.inputs.tag_name }} --notes "${{ github.event.inputs.release_description }}"
        gh release upload ${{ github.event.inputs.tag_name }} \
          sitemap-generator-linux-amd64 \
          sitemap-generator-linux-arm64 \
          sitemap-generator-darwin-amd64 \
          sitemap-generator-darwin-arm64 \
          --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
